# Generated by Django 2.1.5 on 2019-02-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contracts'),
        ),
    ]
