# Generated by Django 2.1.7 on 2019-03-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('servicecontract', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.ServiceContract')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContractShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecontract', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.ServiceContract')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Shop')),
            ],
        ),
    ]
