# Generated by Django 2.1.7 on 2019-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PUBLICIDAD', 'Publicidad'), ('SHOP', 'Tienda')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('amount', models.FloatField(default=0, verbose_name='Costo por Unidad')),
                ('tax', models.FloatField(default=0, verbose_name='Impuestos')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
            ],
        ),
    ]
