# Generated by Django 2.1.7 on 2019-03-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PUBLICIDAD', 'Publicidad'), ('SHOP', 'Planes')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('template_section', models.TextField(blank=True, choices=[('not', 'No aplica'), ('carrusel_inicio', 'Carrusel Inicio'), ('carrusel_destacados', 'Carrusel Destacados'), ('carrusel_tugrow', 'Carrusel Arma Tu Grow'), ('carrusel_rebajas', 'Carrusel Ultimas Rebajas'), ('cinta_promociones', 'Cinta Promociones')], verbose_name='Etique Template')),
                ('priority', models.BooleanField(blank=True, null=True, verbose_name='Destacar')),
                ('amount', models.FloatField(default=0, verbose_name='Costo por Unidad')),
                ('tax', models.FloatField(default=0, verbose_name='Impuestos')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
            ],
        ),
    ]
