# Generated by Django 2.1.7 on 2019-03-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.BooleanField(blank=True, null=True, verbose_name='Destacar'),
        ),
        migrations.AddField(
            model_name='service',
            name='template_section',
            field=models.TextField(blank=True, choices=[('not', 'No aplica'), ('carrusel_inicio', 'Carrusel Inicio'), ('carrusel_destacados', 'Carrusel Destacados'), ('carrusel_tugrow', 'Carrusel Arma Tu Grow'), ('carrusel_rebajas', 'Carrusel Ultimas Rebajas'), ('cinta_promociones', 'Cinta Promociones')], verbose_name='Etique Template'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('PUBLICIDAD', 'Publicidad'), ('SHOP', 'Planes')], max_length=20, verbose_name='Tipo'),
        ),
    ]
