# Generated by Django 2.1.5 on 2019-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Costo por Unidad'),
        ),
        migrations.AddField(
            model_name='service',
            name='tax',
            field=models.FloatField(default=0, verbose_name='Impuestos'),
        ),
        migrations.AddField(
            model_name='service',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
