# Generated by Django 2.1.7 on 2019-04-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/blog/')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slug',)},
        ),
    ]
