# Generated by Django 2.1.7 on 2019-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='titulo'),
        ),
    ]
