# Generated by Django 2.1.7 on 2019-03-18 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='Alias')),
                ('type', models.CharField(blank=True, choices=[('INVOICE', 'Facturacion'), ('DELIVERY', 'Entrega'), ('HOME', 'DOMICILIO')], max_length=20, verbose_name='Tipo de Direccion')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Compañia')),
                ('address1', models.CharField(blank=True, max_length=200, verbose_name='Direccion 1')),
                ('address2', models.CharField(blank=True, max_length=200, verbose_name='Direccion 2')),
                ('postcode', models.CharField(blank=True, max_length=200, verbose_name='Codigo Postal')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Telefono')),
                ('phone_mobile', models.CharField(max_length=200, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='Alias')),
                ('dni_type', models.CharField(blank=True, choices=[('PASAPORTE', 'Pasaporte'), ('RUT', 'RUT'), ('CEDULA', 'Cedula')], max_length=20, verbose_name='Tipo de Documento')),
                ('dni', models.CharField(blank=True, max_length=200, verbose_name='Documento de Identificacion')),
                ('gender', models.CharField(blank=True, choices=[('FE', 'Femenino'), ('MA', 'Masculino'), ('DS', 'Diversidad')], max_length=2, null=True, verbose_name='Genero')),
                ('firts_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('address', models.ManyToManyField(blank=True, to='customers.AddressCustomer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='token')),
                ('type', models.CharField(blank=True, choices=[('PASAPORTE', 'Pasaporte'), ('RUT', 'RUT'), ('CEDULA', 'Cedula')], max_length=20, verbose_name='Tipo de Transaccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
