# Generated by Django 2.1.5 on 2019-02-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresscustomer',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alias'),
        ),
    ]
