# Generated by Django 2.1.5 on 2019-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_addresscustomer_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
    ]
