# Generated by Django 2.1.5 on 2019-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190203_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=200, verbose_name='Documento de Identificacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni_type',
            field=models.CharField(blank=True, choices=[('PASAPORTE', 'Pasaporte'), ('RUT', 'RUT'), ('CEDULA', 'Cedula')], max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('FE', 'Femenino'), ('MA', 'Masculino'), ('DS', 'Diversidad')], max_length=2, verbose_name='Genero'),
        ),
    ]
