# Generated by Django 2.1.7 on 2019-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_mailverification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firts_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
