# Generated by Django 2.1.7 on 2019-03-18 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterActivitySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('click', 'Clicks'), ('search_text', 'Palabra Buscada'), ('search_category', 'Categoria Buscada'), ('view_product', 'Producto Visitado'), ('search_shop', 'Tienda Buscada'), ('search_brend', 'Marca Buscada')], max_length=50, verbose_name='Tipo')),
                ('data', models.CharField(blank=True, max_length=200, null=True, verbose_name='Data')),
                ('datet', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actividad')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
