# Generated by Django 2.1.7 on 2019-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
