# Generated by Django 2.1.7 on 2019-03-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributes',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='productattributes',
            unique_together={('product', 'attributes')},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image')},
        ),
    ]
