# Generated by Django 2.1.7 on 2019-03-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shop_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('url',)},
        ),
    ]
