# Generated by Django 2.1.7 on 2019-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190218_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_temp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Categoria Anterior'),
        ),
    ]
