# Generated by Django 2.1.7 on 2019-03-01 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20190301_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('product', 'user')},
        ),
    ]
